% bifurc(funct,Range,x0,stepsize,N)
%
% This function draws the bifurcation diagram of the dynamical
% system generated by the function  funct  inside the
% region [R(1),R(2)]x[R(3),R(4)].
%
% funct is a function name between commas or a function handle.
%       The function is of the form y = f(x,m).
% Range is an array with the limits of the region of the
%       bifurcation diagram that will be displayed; namely,
%       Range(1) <= m <= Range(2) and Range(3) <= x <= Range(4)
% x0 is the initial value for the iterations of f; namely,
%       x_{n+1} = f(x_n,m) with x_0 = x0.
% stepsize is the step size for m.  The stable periodic orbit
%       of x -> f(x,m) is plotted for m = Range(1), Range(1) + stepsice,
%       Range(1) + 2 stepsice, ..., Range(1) + k stepsice where
%       k = floor((range(2)-range(1))/stepsize).
% N is an array where N(1) is the number of iterations to compute.
%       Only the x_n for N(1)-N(2) < n <= N(1) are plotted.
%       N(2) should be large enought to include periodic orbits
%       with a large period.
%       The default value is [200,100].
%
function bifurc(funct,Range,x0,stepsize,N)
    if ( nargin < 5 )
        N = [200,100];
        if ( nargin < 4 )
            disp("Not enough arguments.")
            disp("Use the help command with bifurc.")
            return;
        end
    end

    if ( (Range(1) > Range(2)) || (Range(3) > Range(4)) )
        disp("Unacceptable values for the range.")
        disp("Use the help command with bifurc.")
        return;
    end

    if ( stepsize <= 0 )
        disp("The step size must be positive.")
        disp("Use the help command with bifurc.")
        return;
    end
    
    figure;
    hold on;

    m = Range(1):stepsize:Range(2);
    s = size(m,2);
    x = x0*ones(1,s);
 
    for i=1:1:N(1)-N(2)
        x = feval(funct,x,m);
    end

    for k = 1:1:N(2)
        x = feval(funct,x,m);
        z = Range(3) <= x & Range(4) >= x;
        m1 = m(z);
        x1 = x(z);
        plot(m1,x1,'.','color','black','markersize',1);
    end

    axis(Range);
    xlabel('\mu');
    ylabel('x');
    hold off;
    display('The drawing is completed.');    
end
